Hopefully fix release/snapshot branch validation

diff --git a/.github/workflows/package-release.yml b/.github/workflows/package-release.yml
--- a/.github/workflows/package-release.yml
+++ b/.github/workflows/package-release.yml
@@ -52,7 +52,7 @@ jobs:
       - name: 'Validate Release Branch'
         if: ${{ inputs.branch }} == 'develop'
         run: |
-          echo "Releases cannot be made from the '${{ inputs.branch }}' branch" && false
+          [ "${{ inputs.branch }}" != 'develop' ] || (echo "Releases cannot be made from the '${{ inputs.branch }}' branch" && false)
 
       - name: Cloning ${{ github.ref }}
         uses: actions/checkout@v2
