Moving inputs to environment variables in run scripts

diff --git a/.github/workflows/publish-package.yml b/.github/workflows/publish-package.yml
--- a/.github/workflows/publish-package.yml
+++ b/.github/workflows/publish-package.yml
@@ -80,12 +80,15 @@ jobs:
     env:
       GITHUB_REF: ${{ github.ref }}
       GITHUB_TOKEN: ${{ github.token }}
+      INPUTS_PACKAGEVERSION: ${{ inputs.package_version }}
+      INPUTS_SOURCEPATH: ${{ inputs.source_path }}
+      INPUTS_UPDATECHANGELOG: ${{ inputs.update_changelog }}
       SOURCE_PATH: '${{ github.workspace }}/${{ inputs.source_path }}'
 
     steps:
       - name: 'Validate version number'
         run: |
-          echo "${{ inputs.package_version }}" | grep -E '^[0-9]+(\.[0-9]+){2}(-SNAPSHOT)?$' || (echo 'Specified version number is invalid -- expected format: x.y.z or x.y.z-SNAPSHOT' && false)
+          echo "${{ env.INPUTS_PACKAGEVERSION }}" | grep -E '^[0-9]+(\.[0-9]+){2}(-SNAPSHOT)?$' || (echo 'Specified version number is invalid -- expected format: x.y.z or x.y.z-SNAPSHOT' && false)
 
       - name: 'Install JDK 17'
         uses: actions/setup-java@v3.4.1
@@ -103,7 +106,7 @@ jobs:
       - name: 'Parse package properties'
         id: 'properties'
         run: |
-          echo "package_name=$(grep -E "^packageName=" ${{ inputs.source_path }}/package.properties | awk '{split($0, a, "="); print a[2]}')" >> $GITHUB_OUTPUT
+          echo "package_name=$(grep -E "^packageName=" ${{ env.INPUTS_SOURCEPATH }}/package.properties | awk '{split($0, a, "="); print a[2]}')" >> $GITHUB_OUTPUT
 
       - name: 'Update changelog'
         if: ${{ !inputs.dry_run && inputs.update_changelog }}
@@ -131,12 +134,12 @@ jobs:
         run: |
           git config user.email "build@jamcity.com"
           git config user.name "Build Machine"
-          if [[ "${{ inputs.update_changelog }}" == "true" ]]; then
+          if [[ "${{ env.INPUTS_UPDATECHANGELOG }}" == "true" ]]; then
             git add CHANGELOG.md
           fi
           git add ${{ inputs.source_path }}/package.json
           git add ${{ inputs.source_path }}/JamCityBuildInfo.cs
-          git commit -m "Files updated for ${{ steps.properties.outputs.package_name }} ${{ inputs.package_version }} release."
+          git commit -m "Files updated for ${{ steps.properties.outputs.package_name }} ${{ env.INPUTS_PACKAGEVERSION }} release."
 
       - name: 'Push changes to GitHub'
         if: ${{ !inputs.dry_run && inputs.push_changes }}
